### ISSUE TITLE
能添加个上拉记载更多 并且可控制么

### ISSUE THREAD

**Issue by nimengbo** [nuptboyzhb/SuperSwipeRefreshLayout#1]
想请问下，只有头的下拉，上拉怎么做比较优雅，直接添加footview觉得耦合性太强了。

**Comment by nuptboyzhb** [comment]
后期有时间加一下

**Comment by mooncafes** [comment]
@nuptboyzhb  能提供下想法吗

**Comment by nuptboyzhb** [comment]
可以添加，上拉加载更多，其思路和下拉刷新一样的。在SuperSwipeRefreshLayout的onInterceptTouchEvent中判断ListView或RecyclerView是否已经滑动到底部，如果没滑动到底部，不拦截touch事件，如果已经滑到底部，再继续上拉，则显示上拉加载更多的View，松手后回调加载更多。

后续有时间，我会加上的。最近加班有点严重

**Comment by predator11** [comment]
Hi, how i can put the refreshing field in down on the screen ? your code don't have any methods to do this (

**Comment by nuptboyzhb** [comment]
已经加上了

**Comment by addappcn** [comment]
@nuptboyzhb 应该把已修复bug 关掉 要不以为都是open的
