### ISSUE TITLE
嵌套ViewPager时，滑动体验不好；

### ISSUE THREAD

**Issue by LuoboDcom** [nuptboyzhb/SuperSwipeRefreshLayout#15]
嵌套ViewPager时，滑动体验不好；且如果是 ViewPager + RecyclerView，recyclerView 头部item会被吃掉

**Comment by wangyeming** [comment]
建议看一下这个回答，http://stackoverflow.com/a/29946734/3941809，谷歌原生的SwipeRefreshLayout也有这个问题，做法很简单，ViewPager滑动时暂时关闭下拉刷新的功能，滑动结束再启动，不过该项目暂时不支持停用下拉刷新或者上拉加载，建议自行添加

**Comment by nuptboyzhb** [comment]
暂停下拉刷新，支持的。禁用直接设置setEnable即可
