### ISSUE TITLE
NestedScrollView监听不到

### ISSUE THREAD

**Issue by Reginer** [nuptboyzhb/SuperSwipeRefreshLayout#25]
需要添加下面代码
else if (mTarget instanceof NestedScrollView){
            NestedScrollView nestedScrollView = (NestedScrollView) mTarget;
            View view = (View) nestedScrollView.getChildAt(nestedScrollView.getChildCount() - 1);
            if (view != null) {
                int diff = (view.getBottom() - (nestedScrollView.getHeight() + nestedScrollView.getScrollY()));
                if (diff == 0) {
                    return true;
                }
            }
        }

**Comment by nuptboyzhb** [comment]
已添加
