### ISSUE TITLE
当item的布局高度大于recyclerview的高度时，无法调用onLoadMore方法

### ISSUE THREAD

**Issue by chendiyou** [nuptboyzhb/SuperSwipeRefreshLayout#34]
当item的布局高度大于recyclerview的高度（单个item无法完整地显示在屏幕中）时，无法调用onLoadMore方法
因为findLastCompletelyVisibleItemPosition返回了-1
改为findLastVisibleItemPosition可以，但是会出现该item没有出来完成loadmore动画已经覆盖了该item

**Comment by chendiyou** [comment]
if (layoutManager instanceof LinearLayoutManager && count > 0) {
                LinearLayoutManager linearLayoutManager = (LinearLayoutManager) layoutManager;
                int lastCompletelyVisibleItemPosition = linearLayoutManager.findLastCompletelyVisibleItemPosition();

                //得到当前显示的最后一个item的view
                View lastChildView = recyclerView.getLayoutManager().getChildAt(recyclerView.getLayoutManager().getChildCount() - 1);
                //得到lastChildView的bottom坐标值
                int lastChildBottom = lastChildView.getBottom();
                //得到Recyclerview的底部坐标减去底部padding值，也就是显示内容最底部的坐标
                int recyclerBottom =  recyclerView.getBottom()-recyclerView.getPaddingBottom();
                //通过这个lastChildView得到这个view当前的position值
                int lastPosition  = recyclerView.getLayoutManager().getPosition(lastChildView);

                //判断lastChildView的bottom值跟recyclerBottom
                //判断lastPosition是不是最后一个position
                //如果两个条件都满足则说明是真正的滑动到了底部
                if(lastCompletelyVisibleItemPosition == count - 1
                        || (lastCompletelyVisibleItemPosition == -1 && lastChildBottom == recyclerBottom
                        && lastPosition == recyclerView.getLayoutManager().getItemCount() - 1 )){
                    mCustomLoadMore = true;
                    return true;
                }

            }

**Comment by chendiyou** [comment]
if (layoutManager instanceof LinearLayoutManager && count > 0) {
                LinearLayoutManager linearLayoutManager = (LinearLayoutManager) layoutManager;
                int lastCompletelyVisibleItemPosition = linearLayoutManager.findLastCompletelyVisibleItemPosition();

                //得到当前显示的最后一个item的view
                View lastChildView = recyclerView.getLayoutManager().getChildAt(recyclerView.getLayoutManager().getChildCount() - 1);
                //得到lastChildView的bottom坐标值
                int lastChildBottom = lastChildView.getBottom();
                //得到Recyclerview的底部坐标减去底部padding值，也就是显示内容最底部的坐标
                int recyclerBottom =  recyclerView.getBottom()-recyclerView.getPaddingBottom();
                //通过这个lastChildView得到这个view当前的position值
                int lastPosition  = recyclerView.getLayoutManager().getPosition(lastChildView);

                //判断lastChildView的bottom值跟recyclerBottom
                //判断lastPosition是不是最后一个position
                //如果两个条件都满足则说明是真正的滑动到了底部
                if(lastCompletelyVisibleItemPosition == count - 1
                        || (lastCompletelyVisibleItemPosition == -1 && lastChildBottom == recyclerBottom
                        && lastPosition == recyclerView.getLayoutManager().getItemCount() - 1 )){
                    return true;
                }

            }

**Comment by chendiyou** [comment]
//如果两个条件都满足则说明是真正的滑动到了底部
            if(lastCompletelyVisibleItemPosition == count - 1
                    || (lastCompletelyVisibleItemPosition == -1 && lastChildBottom == recyclerBottom
                    && lastPosition == recyclerView.getLayoutManager().getItemCount() - 1 )){
                return true;
            }
改成
  //如果两个条件都满足则说明是真正的滑动到了底部
            if(lastCompletelyVisibleItemPosition == count - 1
                    || (lastChildBottom == recyclerBottom
                    && lastPosition == recyclerView.getLayoutManager().getItemCount() - 1 )){
                return true;
            }

**Comment by vadonmo** [comment]
这个写在哪
