### ISSUE TITLE
Android4.3上发现的问题

### ISSUE THREAD

**Issue by FanyangKong** [nuptboyzhb/SuperSwipeRefreshLayout#9]
安卓4.3上拉刷新的时候footerView会鬼畜的跑到屏幕最上面，然后又回到正常位置，换成5.0就不会出现这个问题，不知道哪里出错了

**Comment by houfukude** [comment]
4. API17 我也遇到这个问题 在API19就没这个问题了

**Comment by FanyangKong** [comment]
@houfukude 我pull了一个request解决4.4之前的这个问题，你可以看一下
